# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GoInfoGame' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GoInfoGame

  target 'GoInfoGameTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GoInfoGameUITests' do
    # Pods for testing
  end

end
